services:
  mailman-core:
    image: maxking/mailman-core:0.4.5
    container_name: mailman-core
    hostname: mailman-core
    restart: unless-stopped
    volumes:
    - mailman_core:/opt/mailman/
    stop_grace_period: 30s
    links:
    - mailman-db
    depends_on:
    - mailman-db
    environment:
    - DATABASE_URL=postgresql://mailman:mailmanpass@mailman-db/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    networks:
      - mailman

  mailman-web:
    image: maxking/mailman-web:0.4.5
    container_name: mailman-web
    hostname: mailman-web
    restart: unless-stopped
    depends_on:
    - mailman-db
    links:
    - mailman-core
    - mailman-db
    volumes:
    - mailman_web:/opt/mailman-web-data
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgresql://mailman:mailmanpass@mailman-db/mailmandb
      SECRET_KEY: mcmgg1CB0V2sPCIcTQzchTMIrXgbX7IVEUJ5TuhWdj2YwL8VW1Z
      SERVE_FROM_DOMAIN: wsdb-lists.eliasbistry.de
    networks:
      - mailman

  mailman-db:
    environment:
    - POSTGRES_DB=mailmandb
    - POSTGRES_USER=mailman
    - POSTGRES_PASSWORD=mailmanpass
    image: postgres:12-alpine
    volumes:
    - mailman_db:/var/lib/postgresql/data
    networks:
      - mailman
  mailman-proxy:
    build: ./proxy
    networks:
      - mailman
      - portainer
    volumes:
      mailman_web:/web:ro

volumes:
  mailman_core:
  mailman_web:
  mailman_db:
  
networks:
  mailman:
  portainer:
    external: true
    name: general
